# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b1a6bf95816d6a48ae16183e514c84f1a10c61964cf12b097ae7908907c0103ee598b9653fc9ed71382f4af476671139f7853e78488ef5e41f667adf6e0031d

test:
  secret_key_base: 6d90f5fe8933aa951ef4d7ba410f6bb023715d6d49884b24b1b39549aabaf8d8f2e9c5aed1f9f39e2412c72e002078ca38726c0ce28c316119de710bad839ea0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
